### ISSUE TITLE
2.0 stable support 

### ISSUE THREAD

**Issue by rcpeters** [ORCID/python-orcid#16]
2.0 version of our API is now available on the production registry:
https://groups.google.com/forum/#!msg/orcid-api-users/s7jT29-fqRI/9d3Eos4MCgAJ

**Comment by MSusik** [comment]
Hi!

Great to hear that, I'll try to find some time to implement the changes.

Cheers!

**Comment by ghost** [comment]
Hi, thank you for your package. I second this request. It would be great to see this update.

Here is the documentation of the 2.0 endpoints:

+ [2.0 API Guide at ORCID Source](https://github.com/ORCID/ORCID-Source/tree/master/orcid-model/src/main/resources/record_2.0#calls)
+ [ORCiD update to xsd 2.0](https://members.orcid.org/api/news/xsd-20-update)

**Comment by MSusik** [comment]
@rcpeters @kaplun 

Hi! The work in progress is available in https://github.com/ORCID/python-orcid/tree/2.0update 
I do not have much time available, and it would great if sb could take care of updating the testsuite.

I believe the new version could have the number 1.0.0, but before releasing everything has to be properly tested. There is a change without back compability, the `SearchAPI` class has been removed, as after moving to 2.0 institution credentials are needed in order to get the token. Thus, `SearchAPI` functionalities are integrated into `PublicAPI`.

**Comment by MSusik** [comment]
The 1.0.0 version is now available on PyPI
